theme: jekyll-theme-minimal
title: Welcome to my personal page!
description: This is a home to show any personal and academic projects I've been working on. Enjoy ~
repository: kevin-moses/kevin-moses.github.io.


# 41-56
# DSSP 

# remove tpr file after run 